cmd_/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o := gcc -Wp,-MD,/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/.rbtree.o.d -Wp,-MT,/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o  -D"BUILD_STR(s)=$(pound)s"  -g -I/home/dell/training/linux-raspi-6.8.0-1047/tools/include -I/home/dell/training/linux-raspi-6.8.0-1047/tools/include/uapi -I/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/libbpf/include -I/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/libsubcmd/include  -c -o /home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o ../../lib/rbtree.c

source_/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o := ../../lib/rbtree.c

deps_/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o := \
  /usr/include/stdc-predef.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/rbtree_augmented.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/compiler.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/compiler_types.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/compiler-gcc.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/uapi/asm/bitsperlong.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/asm-generic/bitsperlong.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/rbtree.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/11/include/stdarg.h \
  /usr/include/assert.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/build_bug.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/math.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/panic.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/byteswap.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/uapi/linux/stddef.h \
  /home/dell/training/linux-raspi-6.8.0-1047/tools/include/linux/export.h \

/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o: $(deps_/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o)

$(deps_/home/dell/training/linux-raspi-6.8.0-1047/tools/bpf/resolve_btfids/rbtree.o):
